name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            ENV: ${{secrets.ENV}}
      
        run: |
          echo "$PRIVATE_KEY" > github.pem && chmod 600 github.pem
          ssh -o StrictHostKeyChecking=no -i github.pem ec2-user@ec2-47-129-207-13.ap-southeast-1.compute.amazonaws.com '

              # Now we have got the access of EC2 and we will start the deploy .
              git -C e-com-Fashion-be pull || git clone hhttps://github.com/NBPhuoc0/e-com-Fashion-be.git &&
              cd e-com-Fashion-be &&
              printf "$ENV" > .env &&
              sudo npm i &&
              sudo npm run build &&
              sudo pm2 stop dist/main.js || true &&
              sudo pm2 start dist/main.js
              '