name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Deploy to EC2 using easingthemes/ssh-deploy
  env:
    DATABASE_URL: ${{secrets.DATABASE_URL}}
    DB_HOST: ${{secrets.DB_HOST}}
    DB_PORT: ${{secrets.DB_PORT}}
    DB_USER: ${{secrets.DB_USER}}
    DB_PASS: ${{secrets.DB_PASS}}
    DB_NAME: ${{secrets.DB_NAME}}
    JWT_ACCESS_SECRET: ${{secrets.JWT_ACCESS_SECRET}}
    JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
    REDIS_HOST: ${{secrets.REDIS_HOST}}
    REDIS_PORT: ${{secrets.REDIS_PORT}}
    REDIS_URL: ${{secrets.REDIS_URL}}
    S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
    S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
    S3_BUCKET: ${{secrets.S3_BUCKET}}
    S3_REGION: ${{secrets.S3_REGION}}
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the files
      uses: actions/checkout@v2
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
          
