name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${{secrets.USERNAME }}
            DATABASE_URL: ${{secrets.DATABASE_URL}}
            DB_HOST: ${{secrets.DB_HOST}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_USER: ${{secrets.DB_USER}}
            DB_PASS: ${{secrets.DB_PASS}}
            DB_NAME: ${{secrets.DB_NAME}}
            JWT_ACCESS_SECRET: ${{secrets.JWT_ACCESS_SECRET}}
            JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
            REDIS_HOST: ${{secrets.REDIS_HOST}}
            REDIS_PORT: ${{secrets.REDIS_PORT}}
            REDIS_URL: ${{secrets.REDIS_URL}}
            S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
            S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
            S3_BUCKET: ${{secrets.S3_BUCKET}}
            S3_REGION: ${{secrets.S3_REGION}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/<PROJECT_DIRECTORY> &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              sudo npm i &&
              sudo npm run build &&
              sudo pm2 stop ./dist/main.js &&
              sudo pm2 start ./dist/main.js
              '